//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.06 at 12:55:03 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http:/tech.uc3.cnebrera.com/lesson9", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.cnebrera.uc3.tech.lesson9.model;
